version: '3.9'

services:
    laravel:
        container_name: gove-api
        image: gove-api
        build:
            context: ./api/
            dockerfile: Dockerfile
        volumes:
            - ./api:/var/www/html
            - /var/www/html/vendor
        working_dir: /var/www/html
        ports:
            - "8000:8000"
        env_file:
            - ./api/.env
        networks:
            - laravel-network

    queue:
        image: gove-api
        container_name: gove-api-queue
        restart: always
        working_dir: /var/www/html
        command: php artisan queue:work --queue=default,notifications
        depends_on:
            - laravel
        volumes:
            - ./api/:/var/www/html
            - /var/www/html/vendor
        networks:
            - laravel-network

    scheduler:
        image: gove-api
        container_name: gove-api-scheduler
        restart: always
        working_dir: /var/www/html
        command: php artisan schedule:work
        depends_on:
            - laravel
        volumes:
            - ./api/:/var/www/html
            - /var/www/html/vendor
        networks:
            - laravel-network

    db:
        container_name: db
        image: postgres:16
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        networks:
            - laravel-network

    app:
        container_name: gove-app
        image: gove-app
        build:
            context: ./app/
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - /app/node_modules
            - /app/.next
        ports:
            - "3000:3000"
volumes:
    dbdata: {}

networks:
  laravel-network: