import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/MainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex h-16 px-4 items-center border-b">
          <MainNav className="mx-6" />
        </header>

        <main className="flex flex-col px-12 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
